import test from 'node:test';import assert from 'node:assert/strict';import{createRequire}from'node:module';const require=createRequire(import.meta.url);const PC=require('../product-content.js'),guide=require('../blog/leofoo/leofoo.js');
const rows=Object.values(guide.plans).map(p=>({'品牌':p.brand,'連結':p.url,'類型':'短期','開團日期':'2026-10-02','結束日期':p.end.slice(0,10)}));
test('Public article states the common cutoff and only the booked campfire bread DIY',async()=>{const {readFileSync}=await import('node:fs');const html=readFileSync(new URL('../blog/leofoo/index.html',import.meta.url),'utf8');assert.equal((html.match(/10\/7 23:59/g)||[]).length,4);assert.doesNotMatch(html,/10\/8 23:59|仙草凍/);assert.match(html,/營火麵包 DIY 三人次/);assert.match(html,/leofoo\.js\?v=booking-20261002/);});
test('Leofoo keeps all three human-confirmed campaign plans open through October 7',()=>{const r=guide.resolve(rows,PC,new Date('2026-10-07T23:59:59+08:00'));for(const code of ['A','B','C']){assert.equal(r[code].state,'open');assert.equal(guide.plans[code].end,'2026-10-07T23:59:59+08:00');}assert.equal(PC.campaignFor(rows,'leofoo','2026-10-07').state,'open');});
test('All plans close together at midnight October 8 and stale October 8 Sheet dates cannot reopen them',()=>{for(const time of ['2026-10-08T00:00:00+08:00','2026-10-08T10:00:00+08:00'])for(const code of ['A','B','C'])assert.equal(guide.resolve(rows,PC,new Date(time))[code].state,'closed');const stale=rows.map(r=>({...r,'結束日期':'2026-10-08'}));for(const code of ['A','B','C'])assert.equal(guide.resolve(stale,PC,new Date('2026-10-07T12:00:00+08:00'))[code].state,'unavailable');});
test('Leofoo missing, duplicate, changed URL/date and expired sources fail closed',()=>{for(const changed of [[],[...rows,rows[0]],rows.map((r,i)=>i? r:{...r,'連結':'https://example.com/'}),rows.map((r,i)=>i?r:{...r,'結束日期':'2026-10-09'})])assert.notEqual(guide.resolve(changed,PC,new Date('2026-10-02T12:00:00+08:00')).A.state,'open');assert.equal(guide.resolve(rows,PC,new Date('2026-10-09T00:00:00+08:00')).B.state,'closed');});
test('Room suggestions obey capacities and accessibility, not fake prices',()=>{assert.match(guide.choose({people:5,stairs:'avoid',view:'green',trip:'slow'}).room,/分房/);assert.match(guide.choose({people:7,stairs:'ok',trip:'park'}).room,/分房/);assert.equal(guide.choose({people:4,stairs:'avoid',view:'grass',trip:'animal'}).plan,'B');});
test('Slow stays use C only with its Kenya theme room and accessible alternatives do not pretend Congo is a C room',()=>{const c=guide.choose({people:4,stairs:'ok',view:'blue',trip:'slow'});assert.equal(c.plan,'C');assert.match(c.room,/肯亞斑馬或福豚主題房/);assert.doesNotMatch(c.room,/藍天/);const avoid=guide.choose({people:4,stairs:'avoid',view:'green',trip:'slow'});assert.equal(avoid.plan,'A');assert.match(avoid.room,/剛果單層/);assert.match(avoid.reason,/C 的基本房.*樓梯/);assert.match(avoid.reason,/純住宿續住/);const over=guide.choose({people:7,stairs:'ok',view:'grass',trip:'slow'});assert.equal(over.plan,'A');assert.match(over.room,/分房/);assert.match(over.reason,/不能直接套用 C/);});
test('Blog shelf uses any verified active package, while changed or duplicate plans fail closed individually',()=>{const model=require('../blog/blog-model.js');assert.equal(model.stateForArticle(rows,'leofoo','2026-10-07').shelf,'open');assert.equal(model.stateForArticle(rows,'leofoo','2026-10-08').shelf,'journal');assert.equal(model.stateForArticle(rows.map(r=>({...r,'連結':'https://example.invalid/'})),'leofoo','2026-10-02').shelf,'journal');const changed=rows.map((r,i)=>i===1?{...r,'結束日期':'2026-10-08'}:r);assert.notEqual(guide.resolve(changed,PC,new Date('2026-10-07T10:00:00+08:00')).B.state,'open');assert.notEqual(guide.resolve([...rows,rows[1]],PC,new Date('2026-10-07T10:00:00+08:00')).B.state,'open');});
