import {writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..');
const guide='/trip/guides/bangkok-with-kids/';
const video='https://www.youtube.com/watch?v=f5h0gGdaX2c';
const photo=(name,alt,priority=false)=>`<img src="/trip/assets/${name}.jpg" alt="${alt}" width="1280" height="720" ${priority?'fetchpriority="high"':'loading="lazy"'} />`;
const head=(title,description,path,type='website')=>`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}｜鷹家遠行所</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="https://www.eaglish.store${path}"><meta property="og:type" content="${type}"><meta property="og:title" content="${title}｜鷹家遠行所"><meta property="og:description" content="${description}"><meta property="og:url" content="https://www.eaglish.store${path}"><meta property="og:site_name" content="鷹家遠行所"><meta property="og:locale" content="zh_TW"><meta property="og:image" content="https://www.eaglish.store/trip/assets/bangkok-market.jpg"><meta property="og:image:alt" content="鷹式一家在曼谷市集的旅行畫面"><link rel="icon" href="/icons/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@500;700&family=Noto+Sans+TC:wght@400;500;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/trip/trip.css?v=20260914-journal-1"><script defer src="/site-runtime.js?v=20260914-analytics-v1"></script></head><body><a class="skip" href="#main">跳到主要內容</a><header class="masthead wrap"><a class="brand" href="/trip/" aria-label="鷹家遠行所首頁"><img src="/flights/assets/faraway-wordmark.svg" width="220" height="65" alt="鷹家遠行所"></a><span class="brand-note">把喜歡的地方，變成下一站。<small>EAGLISH TRAVEL JOURNAL</small></span><nav aria-label="主要導覽"><a href="/trip/#destinations">目的地</a><a href="${guide}">旅行筆記</a><a href="/blog/">選物誌 ↗</a></nav></header>`;
const footer=`<footer class="footer"><div class="wrap footer-inner"><a class="brand" href="/trip/"><img src="/flights/assets/faraway-wordmark.svg" width="220" height="65" alt="鷹家遠行所"></a><p>走過的地方，留下喜歡的故事。<br><small>© 鷹式一家 Eaglish Family</small></p><nav aria-label="頁尾導覽"><a href="/">鷹家買物社 ↗</a><a href="/blog/">鷹家選物誌 ↗</a><a href="/trip/flights/">機票與旅行票券 ↗</a></nav></div></footer></body></html>`;
const sectionLabel=(n,en)=>`<p class="eyebrow"><b>${n}</b> / ${en}</p>`;
const home=head('從真實旅行，找到下一站','鷹式一家的旅行故事與自由行靈感。從曼谷市集、親子活動到一頓慢慢吃的飯，把走過的地方整理成你的下一站。','/trip/')+`
<main id="main"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><i class="dot"></i> TAKE A LITTLE DETOUR</p><h1>世界很大，<br>一起<span class="underline">慢慢走。</span></h1><p class="lead">有時候，旅行最值得記得的，<br>不是去了多少地方，<br>而是一起經過的那些小事。</p><a class="button" href="${guide}">從曼谷，開始讀起 <span>↗</span></a><p class="route-note">TAIWAN <span>········ ✈ ········</span> BANGKOK</p></div><div class="postcards"><figure class="postcard main-photo">${photo('bangkok-market','Hiram 在曼谷市集攤位間記錄旅行',true)}<figcaption><span>BANGKOK, THAILAND</span><span>我們的旅行記錄 ↗</span></figcaption></figure><figure class="postcard small-photo">${photo('food-break','Queenie 與孩子在美食街一起吃飯')}<figcaption>走累了，就好好吃一頓。</figcaption></figure><span class="stamp" aria-hidden="true">一路有你<br>LET’S GO!</span></div></section>
<div class="ticker" aria-hidden="true">GO SOMEWHERE YOU’LL REMEMBER <span>✳</span> 不趕路，也是一種旅行 <span>✳</span> STORIES FROM OUR JOURNEYS</div>
<section class="section wrap" id="destinations"><div class="section-heading"><div>${sectionLabel('01','OUR FIRST STOP')}<h2>這一站，曼谷。</h2></div><p>市集的熱鬧、孩子的好奇，<br>還有說改就改的行程。</p></div><a class="feature" href="${guide}"><div class="feature-image">${photo('market-walk','Queenie 與孩子走在曼谷服飾攤位旁')}<span class="photo-label">THAILAND · 曼谷</span></div><div class="feature-copy"><span class="pill">親子旅行</span><span class="pill">市集與室內活動</span><h3>帶孩子去曼谷，<br>把行程留一點空白。</h3><p>逛洽圖洽、找孩子能玩的地方，也允許自己先吃飯、先休息。從我們的真實片段，整理幾個安排旅行的想法。</p><span class="read-link">閱讀曼谷旅行筆記 <span>↗</span></span></div></a></section>
<section class="blue-band"><div class="section wrap"><div class="section-heading"><div>${sectionLabel('02','LITTLE MOMENTS')}<h2>旅行，不只有打卡。</h2></div><p>把一段真實的經驗，<br>留給下一次出發的你。</p></div><div class="cards"><a class="story-card" href="${guide}#market">${photo('bangkok-market','市集走道與旅行中的 Hiram')}<div><p class="eyebrow">01 / 市集裡的小練習</p><h3>讓孩子自己開口，<br>買一樣喜歡的東西。</h3><span class="read-link">看市集片段 ↗</span></div></a><a class="story-card" href="${guide}#indoors">${photo('aquarium-moment','孩子在水族展示區看著水中生物')}<div><p class="eyebrow">02 / 換個步調</p><h3>走進室內，<br>接住孩子的好奇心。</h3><span class="read-link">看室內活動 ↗</span></div></a><a class="story-card" href="${guide}#food">${photo('food-break','親子在美食街共用一餐')}<div><p class="eyebrow">03 / 留時間吃飯</p><h3>好好吃一頓，<br>也是行程的一部分。</h3><span class="read-link">看用餐筆記 ↗</span></div></a></div></div></section>
<section class="closing wrap"><p class="eyebrow"><i class="dot"></i> A JOURNEY WORTH SHARING</p><h2>先聽一個故事，<br>再決定下一站。</h2><p>我們把走過的地方、旅途中的選擇，<br>留在影片，也慢慢整理成文字。</p><a class="button outline" href="${video}" target="_blank" rel="noopener">看完整曼谷旅行影片 ↗</a></section></main>`+footer;

const toc=`<nav class="toc" aria-label="文章目錄"><p class="eyebrow">IN THIS JOURNEY</p><a href="#before">出發前，先想一件事</a><a href="#market">01 洽圖洽市集</a><a href="#museum">02 孩子的活動空間</a><a href="#indoors">03 水族館的片刻</a><a href="#food">04 好好吃一頓</a><a href="#plan">把這些片段放進行程</a><a href="#video">回到完整影片</a></nav>`;
const film=(at,label)=>`<a class="text-link" href="${video}&t=${at}s" target="_blank" rel="noopener">${label} ↗</a>`;
const maps=(q)=>`<a class="button outline" href="https://www.google.com/maps/search/?api=1&amp;query=${encodeURIComponent(q)}" target="_blank" rel="noopener">在 Google Maps 搜尋 ↗</a>`;
const article=head('帶孩子去曼谷，把行程留一點空白','洽圖洽市集、兒童探索博物館、水族館與用餐片段：從鷹式一家的曼谷旅行經驗，整理親子出遊的節奏與行程選擇。',guide,'article')+`
<main id="main"><header class="article-header wrap"><p class="breadcrumbs"><a href="/trip/">鷹家遠行所</a> / 曼谷旅行筆記</p><p class="eyebrow"><i class="dot"></i> BANGKOK / FAMILY JOURNAL</p><h1>帶孩子去曼谷，<br>把行程留一點空白。</h1><p class="article-lead">市集要逛，飯也要慢慢吃。<br>比起把每一站走完，我們更想留下能一起享受的旅程。</p><p class="byline">鷹式一家 · 旅行經驗整理 <span>2026.09.14</span></p><figure class="article-cover">${photo('market-walk','曼谷市集裡，Queenie 和孩子一起逛街',true)}<figcaption>旅行裡的小事，往往比景點清單更讓人記得。</figcaption></figure></header>
<div class="article-layout wrap">${toc}<article class="prose"><section id="before"><div class="quick-note"><p class="eyebrow">這篇適合你，如果……</p><p>你想帶孩子逛市集，也希望保留遊戲、用餐與休息時間。這是一份從旅行影片整理的經驗筆記，不是一張必須逐站完成的行程表。</p></div><h2>先選一件想做的事，<br>剩下的留一點彈性。</h2><p>第一次到曼谷，我們碰到的不只有新鮮感，也有入住等待、孩子不舒服，以及必須臨時調整的安排。原本想做的事，並不一定都能照計畫發生。</p><p>因此，回頭整理這段旅程時，我們更想分享的不是「一天能跑幾個景點」，而是怎麼讓大人和孩子都有享受旅行的空間。以下幾段片刻，可以當作規劃下一趟旅行的起點。</p></section>
<section id="market">${sectionLabel('01','A LITTLE CONVERSATION')}<h2>洽圖洽：買東西，<br>也是練習自己開口。</h2><p>市集對大人可能是逛街，對孩子卻可以是一個練習與人交談的地方。在影片裡，我們聊到出國時讓孩子拿著錢、自己向店員開口，而不是每一次都由父母代勞。</p><figure>${photo('bangkok-market','Hiram 在市集分享讓孩子自己開口購物的想法')}<figcaption>不只看買了什麼，也看孩子如何參與其中。</figcaption></figure><p>不必讓孩子陪著大人一路逛到底。選一樣他感興趣的東西，讓他有參與感，再留時間找地方坐下來。這樣的安排，比把整個市場逛完更適合我們。</p><div class="actions">${maps('Chatuchak Weekend Market Bangkok')}${film(843,'回看市集裡的對談')}</div></section>
<section id="museum">${sectionLabel('02','ROOM TO PLAY')}<h2>逛街之外，<br>也留一站給孩子。</h2><p>市集附近的 Children’s Discovery Museum 兒童探索博物館，是我們這趟留給孩子的一站。影片裡也記錄了當時所在的戶外活動區。那段旅行裡，市集不再是唯一的選項，孩子也有自己的活動空間。</p><blockquote>一位家長陪孩子活動，另一位家長逛街；不是把孩子留下，兩個人都離開。</blockquote><p>若想把這一站放進行程，先查清楚館舍位置、開放日和活動規定。影片中提到的戶外遊具、室內活動與時段，是當時的旅行記錄，不能直接當作現在的開放公告；雨天也不表示所有區域都能使用。</p><div class="actions">${maps("Children's Discovery Museum Chatuchak Bangkok")}${film(1097,'回看館名與活動介紹')}</div></section>
<section id="indoors">${sectionLabel('03','FOLLOW THEIR CURIOSITY')}<h2>換到室內，<br>旅行也可以很有趣。</h2><figure>${photo('aquarium-moment','孩子在水族展示區觀察生物')}<figcaption>離開購物的步調，跟著孩子看看他在意的事。</figcaption></figure><p>這趟旅程也有水族館的片段：孩子看著水中生物，影片後段還記錄了玻璃底船與 4D 電影相關活動。和市集相比，這是另一種一起探索的方式。</p><p>如果你也想安排水族館，建議先選好場館，再確認年齡限制與當天可參加的項目。玻璃底船或電影可能有不同的票種與入場條件，不要只看一張門票的名稱。</p>${film(2289,'回看水族館與玻璃底船片段')}</section>
<section id="food">${sectionLabel('04','MAKE TIME FOR A MEAL')}<h2>走累了，<br>就好好吃一頓。</h2><p>出門前太餓，就先吃飯；逛了一段路，就找地方休息。餐廳和美食街不是景點之間被壓縮的空檔，而是讓一家人重新調整步調的時間。</p><figure>${photo('food-break','Queenie 與孩子在美食街吃飯')}<figcaption>一餐飯，也是一起經過的旅程。</figcaption></figure><p>選餐廳時，不必每一餐都追著名店跑。對帶孩子旅行的我們來說，能坐下來一起吃飯、讓大家喘口氣，本身就是值得留下的片刻。</p>${film(2471,'回看美食街用餐片段')}</section>
<section id="plan"><h2>如果換成你的行程，<br>可以怎麼安排？</h2><p>這些是依經驗整理的安排方式，不代表影片當天的完整行程順序。先確認你想去的地點當天有開，再依天氣與孩子的狀態選擇。</p><div class="plan"><p><b>想逛市集的一天</b><span>選一段洽圖洽 → 留用餐休息時間 → 依體力決定是否加入附近兒童館。不要把市集與所有室內活動都塞在同一天。</span></p><p><b>下雨或需要放慢時</b><span>縮短戶外時間，挑一個已確認能入場的室內活動，再安排一餐。兒童館有戶外部分，別把整館當作完全室內的雨備。</span></p><p><b>狀態不如預期時</b><span>保留取消或調整的空間。這趟原定的烹飪課並未參加，也提醒我們別把每一段空檔都排滿。預約前，也值得先看清退改條件。</span></p></div><details><summary>可以直接照影片中的票價和免費年齡訂票嗎？</summary><p>不建議。那些是拍攝當時提及的條件，還可能受票種與方案影響。請以你準備預訂的場館與方案頁面為準。</p></details><details><summary>這篇有推薦的餐廳或水族館預訂連結嗎？</summary><p>目前沒有。先確認場所名稱與方案適用性，再補上合適的預訂資訊。這不影響你回看影片中的真實旅行片段。</p></details></section>
<section id="video" class="video-end"><p class="eyebrow">THE WHOLE JOURNEY</p><h2>回到故事發生的地方。</h2><p>把鏡頭前後的情境一起看，會更明白我們當時的選擇。</p><a class="button" href="${video}" target="_blank" rel="noopener">看完整曼谷旅行影片 ↗</a><p class="article-return"><a href="/trip/">← 回到鷹家遠行所</a></p></section></article></div></main>`+footer;
mkdirSync(resolve(root,'trip/guides/bangkok-with-kids'),{recursive:true});
writeFileSync(resolve(root,'trip/index.html'),home);
writeFileSync(resolve(root,'trip/guides/bangkok-with-kids/index.html'),article);
console.log('Built travel homepage and Bangkok journal; no private source data included.');
