import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {buildDestinations} from './build-trip-destinations.mjs';
import {bangkokCatalog,bangkokGuide,scene,placeSection,film,esc,media} from './trip-bangkok-places.mjs';
import {routeSection} from './trip-bangkok-routes.mjs';
const root=resolve(import.meta.dirname,'..');
const origin='https://www.eaglish.store';
const title='曼谷親子景點與自由行：8 個實訪地點、Safari World、侏羅紀體驗與 2～5 日行程';
const description='曼谷親子自由行去哪玩？整理恰圖恰、兒童館、SEA LIFE、Safari World、侏羅紀體驗、河濱夜市、暹羅蛇園與老屋餐廳，附實訪照片、地圖、交通、雨備與 2～5 日區域行程。';
const schema=value=>`<script type="application/ld+json">${JSON.stringify(value).replaceAll('<','\\u003c')}</script>`;
const toc=`<nav class="toc guide-nav" data-reading-nav aria-label="文章目錄"><p class="eyebrow">曼谷親子攻略</p><a href="#before">景點與區域總覽</a>${bangkokCatalog.places.map((p,i)=>`<a href="#${p.anchor}">${String(i+1).padStart(2,'0')} ${esc(p.name)}</a>`).join('')}<a href="#food">餐食怎麼接</a><a href="#plan">2～5 日行程組合</a><a href="#rain">雨天如何調整</a><a href="#faq">常見問題</a><a href="#video">兩支原旅行影片</a></nav>`;
const article=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}｜鷹家遠行所</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${origin+bangkokGuide}"><meta property="og:type" content="article"><meta property="og:title" content="${title}｜鷹家遠行所"><meta property="og:description" content="${description}"><meta property="og:url" content="${origin+bangkokGuide}"><meta property="og:site_name" content="鷹家遠行所"><meta property="og:locale" content="zh_TW"><meta property="og:image" content="${origin}/trip/assets/bkk-aquarium-reef.webp"><meta property="og:image:alt" content="SEA LIFE 曼谷海洋世界的水族展示"><link rel="icon" href="/icons/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@500;700&family=Noto+Sans+TC:wght@400;500;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/trip/trip.css?v=20260926-places-1"><link rel="stylesheet" href="/trip/bangkok.css?v=20260926-complete-1"><link rel="stylesheet" href="/blog/reading-nav.css?v=20260926-bkk-1"><script defer src="/blog/reading-nav.js?v=20260926-bkk-1"></script><script defer src="/site-runtime.js?v=20260914-analytics-v1"></script>
${schema({'@context':'https://schema.org','@type':'Article',headline:title,description,inLanguage:'zh-Hant',datePublished:'2026-09-14',dateModified:bangkokCatalog.checkedAt,author:{'@type':'Organization',name:'鷹式一家',url:origin+'/trip/'},publisher:{'@type':'Organization',name:'鷹家遠行所',url:origin+'/trip/'},image:[origin+'/trip/assets/bkk-aquarium-reef.webp',origin+'/trip/assets/bkk-museum-climb.webp'],mainEntityOfPage:origin+bangkokGuide})}
${schema({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[['鷹家遠行所','/trip/'],['泰國','/trip/thailand/'],['曼谷','/trip/thailand/bangkok/'],['曼谷親子景點與行程',bangkokGuide]].map(([name,path],i)=>({'@type':'ListItem',position:i+1,name,item:origin+path}))})}
</head><body class="bkk-guide"><a class="skip" href="#main">跳到主要內容</a><header class="masthead wrap"><a class="brand" href="/trip/" aria-label="鷹家遠行所首頁"><img src="/flights/assets/faraway-wordmark.svg" width="220" height="65" alt="鷹家遠行所"></a><span class="brand-note">出發，找下一個好玩的地方！<small>EAGLISH TRAVEL JOURNAL</small></span><nav aria-label="主要導覽"><a href="/trip/#destinations">目的地</a><a href="/trip/thailand/bangkok/">曼谷攻略</a><a href="/blog/">選物誌 ↗</a></nav></header>
<main id="main"><header class="article-header wrap bkk-header"><nav class="breadcrumbs" aria-label="麵包屑"><a href="/trip/">鷹家遠行所</a> / <a href="/trip/thailand/">泰國</a> / <a href="/trip/thailand/bangkok/">曼谷</a> / <span aria-current="page">親子景點與行程</span></nav><p class="eyebrow"><i class="dot"></i> BANGKOK / FAMILY GUIDE</p><h1>曼谷親子自由行<br><span>市集、動物園與侏羅紀體驗</span></h1><p class="article-lead">8 個我們去過的景點與餐廳，從市區到河畔、動物園一次整理。<br>先挑孩子喜歡的活動，再用 2～5 日路線接好交通、用餐和雨天備案。</p><p class="byline">撰文・影像：鷹式一家 <span>更新 2026.09.26</span></p><div class="bkk-hero"><figure class="bkk-hero-main">${scene('bkk-aquarium-reef',{priority:true})}<figcaption>SEA LIFE · 近看水中生物</figcaption></figure><figure>${scene('bkk-safari-giraffes',{priority:true,card:true})}<figcaption>SAFARI WORLD · 看長頸鹿</figcaption></figure><figure>${scene('bkk-jurassic-dinosaur',{priority:true,card:true})}<figcaption>JURASSIC WORLD · 恐龍場景</figcaption></figure></div></header>
<div class="article-layout wrap">${toc}<article class="prose"><section id="before"><h2>曼谷親子景點怎麼選？先分成五個區域</h2><p><strong>恰圖恰</strong>把市集和兒童館排一起；<strong>Chit Lom／Siam</strong>串老屋用餐、水族館和百貨；<strong>Safari World</strong>專留完整白天；<strong>Asiatique</strong>接侏羅紀體驗與河畔晚餐；<strong>暹羅蛇園</strong>則是機場區半日選項。看似都在曼谷，不能當成彼此走路就到。</p><p>我們把兩支影片走過的地方拆成獨立景點。你可以只選市區兩天，也能加上郊區與河畔；實際經驗放在各站的小故事裡，行程則依現在想怎麼玩來重新安排。</p><div class="bkk-overview">${bangkokCatalog.places.map(p=>`<a href="#${p.anchor}" data-place-ref="${p.id}"><strong>${p.name}</strong><span>${p.kind}</span><small>${p.area} · ${p.duration}</small></a>`).join('')}</div><div class="actions"><a class="button" href="#plan">選 2～5 日行程 ↓</a><a class="text-link" href="#rain">看雨天替換 ↓</a></div></section>
${bangkokCatalog.places.map(placeSection).join('')}
<section id="food"><p class="eyebrow"><b>EAT</b> / FOOD ALONG THE ROUTE</p><h2>吃飯接在哪裡？跟著當天區域選</h2><h3>恰圖恰：午餐放在市集和兒童館之間</h3><p>上午逛完先吃熟食、找座位補水，再前往兒童館。人潮多時提早找餐飲，避免孩子餓了還在市場深處找出口。下午補逛或休息，晚餐回住宿附近挑選，不必再跑另一個遠端景點。</p><h3>Chit Lom／Siam：老屋早午餐，或水族館同棟吃</h3><p><a href="#baanlangsuan">Baan Langsuan</a> 是我們實際吃過的老屋餐廳；要先用餐再去水族館，兩站之間另留移動時間。想少走路或遇到大雨，直接把午餐、點心與晚餐放在 <a href="https://www.google.com/maps/search/?api=1&amp;query=Siam%20Paragon%20Bangkok" target="_blank" rel="noopener">Siam Paragon（Google Maps）</a> 的餐廳與美食街，會更好掌握時間。</p><h3>Safari World：先看門票附不附午餐</h3><p>有些票券含餐、有些只有入場，不要到了園區才發現方案不同。安排一段坐下用餐的時間，下午再繼續看動物；返城晚餐依飯店位置安排。影片中當年吃過的一餐，不代表現在所有園內餐廳的菜單或品質。</p><h3>河畔：Asiatique 用餐不用再轉車</h3><p>去完侏羅紀體驗，可以在 <a href="#asiatique">Asiatique</a> 同區找晚餐。這裡有餐廳、飲品和商店，先看座位、菜單和等候時間；若想看夜景，天氣允許再走到河畔。我們當天沒有留到晚餐，這段是為方便安排行程加上的延伸。</p><h3>機場區：蛇園餐飲先問，再決定是否留園內吃</h3><p>我們這次有在園內咖啡區吃東西，但不保證你到訪日一定供應相同餐點。先向館方確認供餐時間；有機場區住宿的人，也可以把午餐安排回飯店，避免為一餐再往市中心折返。</p></section>
${routeSection()}
<section id="faq"><h2>曼谷親子行程常見問題</h2><details><summary>這是影片裡的第一天和第二天嗎？</summary><p>不是。第一支影片本身就涵蓋恰圖恰、兒童館，以及隔天的老屋餐廳和水族館；第二支又有動物園、水上市場、侏羅紀體驗與蛇園等不同日程。本文的 A～E 是按地理位置重組的遊玩路線，不把影片集數當旅行天數。</p></details><details><summary>只有兩天，要選哪幾個地方？</summary><p>碰到週末可以選 A 恰圖恰和 B 水族館；喜歡恐龍、想少一點戶外步行，可用 D 河畔組合換掉 A。很想去 Safari World，就把其中一天完整留給 C，不要上午市集、下午再衝動物園。</p></details><details><summary>只有下午有時間，也能參考嗎？</summary><p>可以。D 是下午到晚上的路線；B 可以省略老屋餐廳，直接水族館加同棟用餐。A、C 的戶外行程受到營業與閉園時間限制，不適合照原表從下午開始平移。</p></details><details><summary>玻璃底船、遊園車都包含在門票嗎？</summary><p>不一定。SEA LIFE 的玻璃底船與 4D 電影、Safari World 的雙園入場與車遊，都是需要核對的項目。看同一天、相同旅客條件的方案明細，再比較總價；園內遊園車也不等於飯店接送。</p></details><details><summary>帶推車去侏羅紀體驗方便嗎？</summary><p>官方目前不允許推車進入體驗區，售票附近有遮蔽停放處。帶小小孩要先想好抱行方式。聲光與突發效果也可能讓孩子害怕，不因為是恐龍主題就假設適合所有年齡。</p></details><details><summary>蛇園能安排在離境前嗎？</summary><p>要看開館時間、住宿、班機和報到要求。它在素萬那普機場一帶，不代表可以壓著時間玩；上午或中午起飛通常不適合。本文 E 是可選半日，並非保證接得上班機的安排。</p></details></section>
<section id="video" class="video-end"><p class="eyebrow">OUR BANGKOK TRIP</p><h2>想看現場？這兩支影片接著看</h2><p>上面先幫你選地點與排路線，影片則可以看孩子的反應、動物園車遊、恐龍場景和展覽環境。</p>${bangkokCatalog.videos.map(v=>`<h3>${esc(v.label)}</h3><p>${esc(v.coverage)}</p><a class="text-link" href="${esc(v.url)}" target="_blank" rel="noopener">看完整旅行影片 ↗</a>`).join('')}<div class="actions">${film(1097,'兒童館遊戲')}${film(2370,'玻璃底船')}${film(670,'Safari World 長頸鹿',bangkokCatalog.videos[1].url)}${film(1645,'侏羅紀場景',bangkokCatalog.videos[1].url)}</div><p class="article-return"><a href="/trip/thailand/bangkok/">← 看全部曼谷景點卡</a></p></section></article></div></main>
<footer class="footer"><div class="wrap footer-inner"><a class="brand" href="/trip/"><img src="/flights/assets/faraway-wordmark.svg" width="220" height="65" alt="鷹家遠行所"></a><p>出發，找下一個好玩的地方！<br><small>© 鷹式一家 Eaglish Family</small></p><nav aria-label="頁尾導覽"><a href="/">鷹家買物社 ↗</a><a href="/blog/">鷹家選物誌 ↗</a><a href="/trip/thailand/">泰國自由行 ↗</a></nav></div></footer></body></html>`;
mkdirSync(resolve(root,'trip/guides/bangkok-with-kids'),{recursive:true});
writeFileSync(resolve(root,'trip/guides/bangkok-with-kids/index.html'),article);
writeFileSync(resolve(root,'trip/assets/bkk-media.json'),JSON.stringify(Object.entries(media).map(([id,m])=>({id,source:(m.video?`https://www.youtube.com/watch?v=${m.video}`:bangkokCatalog.video)+`&t=${m.second}s`,kind:'owned-video-frame',creator:'鷹式一家',reviewedAt:bangkokCatalog.checkedAt,alt:m.alt,crop:m.crop||[0,0,1920,1080],width:m.width||1440,height:m.height,variants:['','-640','-960'].map(suffix=>{const file=`/trip/assets/${id}${suffix}.webp`,buffer=readFileSync(resolve(root,'.'+file));return {file,bytes:buffer.length,sha256:createHash('sha256').update(buffer).digest('hex')};})})),null,2)+'\n');
buildDestinations(root);
console.log('Built place-first Bangkok guide and shared destination cards.');
