import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {buildDestinations} from './build-trip-destinations.mjs';
import {bangkokCatalog,bangkokGuide,scene,placeSection,film,esc,media} from './trip-bangkok-places.mjs';
const root=resolve(import.meta.dirname,'..');
const origin='https://www.eaglish.store';
const title='曼谷親子景點與兩日行程：恰圖恰、兒童探索博物館、SEA LIFE 水族館';
const description='曼谷帶孩子去哪玩？介紹恰圖恰週末市集、兒童探索博物館、SEA LIFE 曼谷海洋世界與玻璃底船，附實訪照片、交通、Google Maps、門票方案及兩日順路安排。';
const schema=value=>`<script type="application/ld+json">${JSON.stringify(value).replaceAll('<','\\u003c')}</script>`;
const toc=`<nav class="toc guide-nav" data-reading-nav aria-label="文章目錄"><p class="eyebrow">曼谷親子攻略</p><a href="#before">景點與區域總覽</a><a href="#market">01 恰圖恰週末市集</a><a href="#museum">02 兒童探索博物館</a><a href="#indoors">03 SEA LIFE 水族館</a><a href="#food">午餐怎麼接</a><a href="#plan">兩日行程與雨備</a><a href="#faq">常見問題</a><a href="#video">我們的旅行影片</a></nav>`;
const article=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}｜鷹家遠行所</title><meta name="description" content="${description}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${origin+bangkokGuide}"><meta property="og:type" content="article"><meta property="og:title" content="${title}｜鷹家遠行所"><meta property="og:description" content="${description}"><meta property="og:url" content="${origin+bangkokGuide}"><meta property="og:site_name" content="鷹家遠行所"><meta property="og:locale" content="zh_TW"><meta property="og:image" content="${origin}/trip/assets/bkk-aquarium-reef.webp"><meta property="og:image:alt" content="SEA LIFE 曼谷海洋世界的水族展示"><link rel="icon" href="/icons/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@500;700&family=Noto+Sans+TC:wght@400;500;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/trip/trip.css?v=20260926-places-1"><link rel="stylesheet" href="/trip/bangkok.css?v=20260926-tab-6"><link rel="stylesheet" href="/blog/reading-nav.css?v=20260926-bkk-1"><script defer src="/blog/reading-nav.js?v=20260926-bkk-1"></script><script defer src="/site-runtime.js?v=20260914-analytics-v1"></script>
${schema({'@context':'https://schema.org','@type':'Article',headline:title,description,inLanguage:'zh-Hant',datePublished:'2026-09-14',dateModified:bangkokCatalog.checkedAt,author:{'@type':'Organization',name:'鷹式一家',url:origin+'/trip/'},publisher:{'@type':'Organization',name:'鷹家遠行所',url:origin+'/trip/'},image:[origin+'/trip/assets/bkk-aquarium-reef.webp',origin+'/trip/assets/bkk-museum-climb.webp'],mainEntityOfPage:origin+bangkokGuide})}
${schema({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[['鷹家遠行所','/trip/'],['泰國','/trip/thailand/'],['曼谷','/trip/thailand/bangkok/'],['曼谷親子景點與行程',bangkokGuide]].map(([name,path],i)=>({'@type':'ListItem',position:i+1,name,item:origin+path}))})}
</head><body class="bkk-guide"><a class="skip" href="#main">跳到主要內容</a><header class="masthead wrap"><a class="brand" href="/trip/" aria-label="鷹家遠行所首頁"><img src="/flights/assets/faraway-wordmark.svg" width="220" height="65" alt="鷹家遠行所"></a><span class="brand-note">出發，找下一個好玩的地方！<small>EAGLISH TRAVEL JOURNAL</small></span><nav aria-label="主要導覽"><a href="/trip/#destinations">目的地</a><a href="/trip/thailand/bangkok/">曼谷攻略</a><a href="/blog/">選物誌 ↗</a></nav></header>
<main id="main"><header class="article-header wrap bkk-header"><nav class="breadcrumbs" aria-label="麵包屑"><a href="/trip/">鷹家遠行所</a> / <a href="/trip/thailand/">泰國</a> / <a href="/trip/thailand/bangkok/">曼谷</a> / <span aria-current="page">親子景點與行程</span></nav><p class="eyebrow"><i class="dot"></i> BANGKOK / FAMILY GUIDE</p><h1>曼谷親子景點與兩日行程<br><span>恰圖恰、兒童館與水族館怎麼玩？</span></h1><p class="article-lead">到恰圖恰逛小店、在兒童館玩攀爬，隔天去 Siam 看鯊魚、搭玻璃底船！<br>三個我們去過的景點，整理好交通、玩法與用餐動線，第一次帶孩子來曼谷也能照著安排。</p><p class="byline">撰文・影像：鷹式一家 <span>更新 2026.09.26</span></p><div class="bkk-hero"><figure class="bkk-hero-main">${scene('bkk-aquarium-reef',{priority:true})}<figcaption>SEA LIFE · 近看水中生物</figcaption></figure><figure>${scene('bkk-market-stalls',{priority:true,card:true})}<figcaption>CHATUCHAK · 市集尋寶</figcaption></figure><figure>${scene('bkk-museum-climb',{priority:true,card:true})}<figcaption>CHILDREN’S MUSEUM · 攀爬與遊戲</figcaption></figure></div></header>
<div class="article-layout wrap">${toc}<article class="prose"><section id="before"><h2>先看地點：恰圖恰一天，Siam 一天</h2><p>恰圖恰市集與兒童探索博物館位於同一帶，適合一起安排；SEA LIFE 在 Siam Paragon 百貨，和百貨用餐排成另一個半日到一日行程。下面是依區域重新編排的兩天路線，不是影片逐站播放的順序。</p><div class="bkk-overview">${bangkokCatalog.places.map(p=>`<a href="#${p.anchor}" data-place-ref="${p.id}"><strong>${p.name}</strong><span>${p.kind}</span><small>${p.area} · ${p.duration}</small></a>`).join('')}</div><div class="actions"><a class="button" href="#plan">先看兩日行程 ↓</a><a class="text-link" href="#indoors">下雨？直接看水族館 ↓</a></div></section>
${bangkokCatalog.places.map(placeSection).join('')}
<section id="food"><p class="eyebrow"><b>04</b> / LUNCH STOPS</p><h2>午餐跟著區域安排</h2><h3>恰圖恰：逛完先吃，再進兒童館</h3><p>建議先逛市集約一個半小時，接著用餐、補水，再前往兒童館。想簡單吃，就挑市集現場的熟食攤；需要冷氣與較完整的座位，可以先在地圖找附近商場餐飲。不要等孩子已經很餓，才從市場最深處開始找出口。</p><h3>Siam：水族館搭配 Siam Paragon 用餐</h3><p>水族館就在百貨裡，可以先吃午餐，再依預訂時間入場；上午先參觀的人，結束後直接在同棟挑餐廳或美食街也方便。這樣下雨時不必為了一餐再走一段室外路。這裡提供的是兩個區域的用餐動線，實際餐廳可依當天菜單與空位選擇。</p></section>
<section id="plan"><p class="eyebrow"><b>05</b> / TWO DAYS IN BANGKOK</p><h2>曼谷親子兩日行程這樣排</h2><p>時間是規劃額度，可依住宿位置與入場場次調整。若旅程中只有一天是假日，就優先把恰圖恰排在那一天。</p><div class="bkk-day"><h3>Day 1｜恰圖恰週末市集＋兒童探索博物館</h3><ol><li><time>09:30</time><div><a href="#market">恰圖恰市集</a><p>選兩三種想逛的東西，先看小店與攤位。</p></div></li><li><time>11:00</time><div>午餐、補水與前往兒童館<p>預留找座位、上廁所和戶外步行時間，不把兩站當成出門就到。</p></div></li><li><time>12:30</time><div><a href="#museum">兒童探索博物館</a><p>先問當日活動，安排約兩小時玩遊具與參觀；戲水與工作坊依現場場次。</p></div></li><li><time>14:30</time><div>結束主要行程<p>若還想買東西，可以分頭由一位大人逛街、另一位陪孩子休息。</p></div></li></ol></div><div class="bkk-day"><h3>Day 2｜Siam 水族館＋玻璃底船＋百貨用餐</h3><ol><li><time>10:00</time><div><a href="#indoors">SEA LIFE 水族館</a><p>預約這個時段前，先確認入場方式；水族展示和船班順序依現場安排。</p></div></li><li><time>13:00</time><div>Siam Paragon 午餐<p>若船班或加購活動較晚，調整午餐時間，並確認能否再次入場。</p></div></li><li><time>14:00</time><div>百貨逛街或回飯店<p>喜歡購物可以繼續逛，帶小小孩則很適合接午睡。</p></div></li></ol></div><aside class="bkk-rain"><h3>遇到大雨：把 Siam 日往前換</h3><p>尚未訂固定日期票時，可以先安排室內水族館。若已購票，先確認能否改期。兒童館有室內區，但到館步行、攀爬網與沙坑都涉及戶外，不能把整站當成完全不淋雨的備案。</p></aside></section>
<section id="faq"><h2>曼谷親子行程常見問題</h2><details><summary>平日也能照這條恰圖恰路線走嗎？</summary><p>兒童館週二到週日開放，但市集平日不是全區營業。想完整逛購物攤位，優先安排週六或週日；週一也不要把兒童館排進去。</p></details><details><summary>三個景點可以一天玩完嗎？</summary><p>這份行程不建議。市集與兒童館各留約兩小時，加上用餐和交通已占大半天；再趕到 Siam 玩水族館，玻璃底船與孩子休息都容易被壓縮。只有一天時，選恰圖恰組合或 Siam 組合就好。</p></details><details><summary>買水族館門票就能搭玻璃底船嗎？</summary><p>不一定。基本入場、玻璃底船和 4D 電影可能分開販售，也有套票。請看所選方案的包含項目、年齡限制與當天場次，不能只用產品大標題判斷。</p></details><details><summary>帶推車適合嗎？</summary><p>市集巷道與人潮較不好推，兒童館也有戶外動線。安排接送與進百貨時，預留找電梯、收推車和安檢的時間；要搭玻璃底船，另向館方確認推車寄放。</p></details></section>
<section id="video" class="video-end"><p class="eyebrow">OUR BANGKOK TRIP</p><h2>想看孩子實際怎麼玩？</h2><p>這篇整理的是景點與行程；影片裡還有我們逛市集、玩兒童館和看海洋生物的現場反應。</p><div class="actions">${film(742,'恰圖恰逛街')}${film(1090,'兒童館遊戲')}${film(2350,'玻璃底船體驗')}</div><a class="button" href="${esc(bangkokCatalog.video)}" target="_blank" rel="noopener">看完整曼谷旅行影片 ↗</a><p class="article-return"><a href="/trip/thailand/bangkok/">← 看曼谷景點卡</a></p></section></article></div></main>
<footer class="footer"><div class="wrap footer-inner"><a class="brand" href="/trip/"><img src="/flights/assets/faraway-wordmark.svg" width="220" height="65" alt="鷹家遠行所"></a><p>出發，找下一個好玩的地方！<br><small>© 鷹式一家 Eaglish Family</small></p><nav aria-label="頁尾導覽"><a href="/">鷹家買物社 ↗</a><a href="/blog/">鷹家選物誌 ↗</a><a href="/trip/thailand/">泰國自由行 ↗</a></nav></div></footer></body></html>`;
mkdirSync(resolve(root,'trip/guides/bangkok-with-kids'),{recursive:true});
writeFileSync(resolve(root,'trip/guides/bangkok-with-kids/index.html'),article);
writeFileSync(resolve(root,'trip/assets/bkk-media.json'),JSON.stringify(Object.entries(media).map(([id,m])=>({id,source:bangkokCatalog.video+`&t=${m.second}s`,kind:'owned-video-frame',creator:'鷹式一家',reviewedAt:bangkokCatalog.checkedAt,alt:m.alt,crop:m.crop||[0,0,1920,1080],width:1440,height:m.height,variants:['','-640'].map(suffix=>{const file=`/trip/assets/${id}${suffix}.webp`,buffer=readFileSync(resolve(root,'.'+file));return {file,bytes:buffer.length,sha256:createHash('sha256').update(buffer).digest('hex')};})})),null,2)+'\n');
buildDestinations(root);
console.log('Built place-first Bangkok guide and shared destination cards.');
